feat : Added Wishlist and Cart
Bharatrathod-81/marvel-fashion pull request #4
Opened 2022-04-05 12:32 UTC by Bharatrathod-81

Added cart page and wishlist page 
Used useReducer  and Context

2022-04-05 12:48 UTC, tanishk15sharma approved these changes
You can use a code editor like `prettier` for better readability . in some places you are using `{}` even for single line of code you can correct it . 
I liked that your reducer file is separate .

2022-04-05 12:48 UTC, tanishk15sharma commented on src/components/cart-listing/cart-listing.jsx
> +                                         onClick={() => {
No need to use curly braces `{}` here .

2022-04-05 17:16 UTC, nikk422 approved these changes

2022-04-05 17:16 UTC, nikk422 commented on src/components/cart-listing/cart-listing.css
> +    color: gray;
you can use global variable for repeating color....

2022-04-05 18:47 UTC, Omkar-Chaskar reviewed
code is clean and well written.
components are well structured.
Just Simple suggestion , In css file flex property in been used many times.
You can initiate use new class which contain flex property as we done in our Component Library for Code reduction.

2022-04-06 00:31 UTC, ashishnnnnn requested changes

2022-04-06 00:31 UTC, ashishnnnnn commented on src/components/single-product/single-product.jsx
> +                <img className="card-Img" src={data.image}/>
These images could have alt attribute..

2022-04-06 04:51 UTC, merged